### ISSUE TITLE
Webpack: "Module build failed: Error: Cannot find module 'babel-runtime/helpers/interop-export-wildcard'"

### ISSUE THREAD

**Issue by gnestor** [thejameskyle/babel-setup-react-transform#3]
I'm getting the following error running Webpack with  babel-plugin-react-transform@2.0.0-beta1:

```
ERROR in ./scripts/index.js
Module build failed: Error: Cannot find module 'babel-runtime/helpers/interop-export-wildcard'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-function-name/node_modules/babel-types/lib/index.js:13:30)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
 @ multi main
```

This is obviously babel-runtime throwing the error (and not babel-plugin-react-transform), but I'd like to start a thread about how to successfully config Webpack with Babel 6 and babel-plugin-react-transform.

webpack.config.js
```javascript
var webpack = require('webpack');
var path = require('path');
module.exports = {
  entry: [
    'webpack-dev-server/client?http://localhost:8080',
    'babel-polyfill',
    './src/index'
  ],
  output: {
    path: __dirname,
    filename: 'bundle.js',
    publicPath: '/static/'
  },
  resolve: {
    extensions: ['', '.js']
  },
  devtool: 'eval-source-map',
  plugins: [
    new webpack.NoErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('development')
      }
    }),
  ],
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel',
        include: path.join(__dirname, 'scripts')
      },
      {
        test: /\.scss$/,
        loaders: [
          'style',
          'css?sourceMap',
          'autoprefixer-loader?browsers=last 2 versions',
          'sass?sourceMap'
        ]
      }
    ]
  }
};
```

.babelrc
```json
{
  "presets": ["es2015", "stage-0", "react"],
  "env": {
    "development": {
      "plugins": [
        ["react-transform", {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }]
        }],
        "transform-runtime"
      ],
      "cacheDirectory": true
    }
  }
}
```

package.json
```json
{
  "scripts": {
    "start": "webpack-dev-server --hot --inline --progress --colors --history-api-fallback",
  "dependencies": {
    "babel-polyfill": ">=6.3.14",
    "babel-runtime": ">=6.3.13",
    "react": ">=0.14.0",
    "react-dom": ">=0.14.0",
  },
  "devDependencies": {
    "autoprefixer-loader": ">=3.1.0",
    "babel-core": ">=6.3.15",
    "babel-loader": ">=6.2.0",
    "babel-plugin-react-transform": "2.0.0-beta1",
    "babel-preset-es2015": ">=6.3.13",
    "babel-preset-react": ">=6.3.13",
    "babel-preset-stage-0": ">=6.3.13",
    "css-loader": ">=0.20.2",
    "react-transform-hmr": ">=1.0.1",
    "sass-loader": ">=3.1.1",
    "webpack": ">=1.12.2",
    "webpack-dev-server": ">=1.8.0",
  }
}

```

**Comment by thejameskyle** [comment]
This is not the right place for Babel support queries, especially not for things unrelated to react-transform.

You can go to https://discuss.babeljs.io or https://slack.babeljs.io.

I don't want to start a thread about webpack here as this is not right place for it.

**Comment by EasonWang01** [comment]
Just reinstall babel-core solve my problem

`npm install babel-core`

**Comment by elenaHristova** [comment]
@gnestor  How did you handle it? I have the same issue

**Comment by gnestor** [comment]
@elenaHristova This was a year ago so I don't remember, but here is a working .babelrc using babel 6: https://github.com/gnestor/react-webpack-starter/blob/master/.babelrc

**Comment by elenaHristova** [comment]
@gnestor  Thank you very much for the fast reply! I saw but I still wonder about this 
interop-export-wildcard.js file which obviously does not exist in the babel-runtime/helpers.
